### PR TITLE
Promise API

### LINKED ISSUE #52: Promise API
Hi,
Thanks for your work!
It would be great to have a promise API in this lib, allowing for async/await compatibility. Would you accept such a PR ?

### PR DESCRIPTION
**Pull request by IcanDivideBy0**
fixes #52

### CODE REVIEW

**Comment by eXeDK** [comment]
I haven't tested this yet but from a quick glance shouldn't it just use Promises and not Promises and callbacks?

**Comment by IcanDivideBy0** [comment]
Well @remixz asked for a non breaking change, so callbacks are still supported: the requests are now managed by promises, which will then invoke callbacks if provided. The promise is always returned (an async function with callback will never have anything meaningful to return anyways, simpler to always return promise)

**Comment by IcanDivideBy0** [comment]
Maybe I should switch to `request-native-promise` if you guys want to avoid `bluebird` dependency ?

**Comment by eXeDK** [comment]
Aren't you only returning promises on reject? As I see it the continued use of callbacks together with promises on rejects seems silly.

I don't know about @remixz but I prefer bluebird over native promises.

**Comment by IcanDivideBy0** [comment]
Hmm promise a always returned, on reject and fulfil. This pattern works like a charm, what's so "silly" ? If you don't get it, you still can test it yourself :
```js
const httpResult = {
  error: null,
  foo: 'bar'
}

function test(cb) {
  return Promise.resolve(httpResult)
  .then(body => {
    if (body.error) return Promise.reject(body.error)
    if (!cb) return body
    cb(null, body)
  })
  .catch(err => {
    if (!cb) return Promise.reject(err)
    cb(err)
  })
}

test().then(console.log).catch(console.error)
test(console.log)
```

**Comment by IcanDivideBy0** [comment]
As of bluebird, i see it as an unnecessary orverhead for such a lib, but does not matters that much

**Comment by eXeDK** [comment]
Seems I've missed the Promise.resolve twice for some reason. Sorry about that ;-)

**Comment by flore2003** [comment]
Any news on this? Looks like a good addition and works like a charm

**Comment by eXeDK** [comment]
Maybe @remixz has some comments?

**Comment by eXeDK** [comment]
I think time is due to merge this since @remixz has yet to comment on it. 

Have a great Christmas everyone

**Pull request merged**
