### PR TITLE
Nitrous.io Quickstart button

### PR DESCRIPTION
**Pull request by yeouchien**
Added Nitrous Quickstart files so anyone can quickly spin up a free, cloud dev environment to start using this repo. Clicking the Quickstart button will automatically clone this repo and will install and configure any required packages.

### CODE REVIEW

**Comment by maciekmm** [comment]
Hello @yeouchien,

first of all: thanks for contributing!
As you can see the build failed with a reason of using inadequate coding style.
The "Echo..." message should be surrounded bu single quotes not backticks.
```js
console.log(`Echo bot server running at port 3000.`)
```
It'd be awesome if you fixed that.

Tip: You should run `npm test` before commiting :)

**Comment by yeouchien** [comment]
Hi @maciekmm, I've fixed that. My mistake. :smile:

**Comment by maciekmm** [comment]
Well done @yeouchien !
Now you have to wait for @remixz to decide whether he wants the feature or not :)

Great work :+1:

**Comment by remixz** [comment]
This is neat @yeouchien! I've added it with b8b7335, just changed the instructions a bit, so it's more inline with the Examples section. Thanks! 😄

**Pull request closed without merging**
