### PR TITLE
Adds extra fields for the user profile

### PR DESCRIPTION
**Pull request by victorcotap**
According to the [documentation](https://developers.facebook.com/docs/messenger-platform/implementation#user_profile_api), Facebook provides more fields than just first name, last name and profile pic to the call we can make with getProfile

This changes adds the extra fields

### CODE REVIEW

**Comment by kittrCZ** [comment]
Hi guys! Thanks for great package, do you guys think that this will make it to master?

**Comment by remixz** [comment]
Oh, nice! Looks like they added those new fields recently, as they weren't there when the API first came out. Great work, thanks! 😄

**Comment by remixz** [comment]
Released as v2.3.0.

**Comment by victorcotap** [comment]
They keep adding stuff without documentation, for example there is now a 'location' type message that we can receive that is nowhere to be found in the docs :D

**Comment by kittrCZ** [comment]
@victorcotap how did you find out? What kind of message is that? Do you have more info about it?

**Comment by victorcotap** [comment]
Just send your bot a location message using the messenger app.
I found out by watching the app review example video from Facebook...

**Comment by kittrCZ** [comment]
@victorcotap exciting. location will be big gamechanger....

**Pull request merged**
