### PR TITLE
fixing forEach undefined error

### PR DESCRIPTION
**Pull request by ianhayes**
referencing https://github.com/remixz/messenger-bot/issues/77

### CODE REVIEW

**Comment by eXeDK** [comment]
Please fix the linting :-)

**Comment by ianhayes** [comment]
I'm sorry, I'm not sure what you mean. Can you give mow information please? What errors?

**Comment by eXeDK** [comment]
See the details of the Travis CI build that failed right below this comment

**Comment by ianhayes** [comment]
@eXeDK sorry I couldn't see the checks on my phone, everything passes now :)

**Comment by camilaavilarinho** [comment]
I'm using the last version and this error is still happening

**Pull request merged**
