### PR TITLE
Add possibility of sending message with tag

### PR DESCRIPTION
**Pull request by baudev**
Add the function `sendMessageWithTag(recipient, payload, tag, cb)` which allows sending messages with the specified tag.

Example of usage : 
``` Node
bot.sendMessageWithTag(payload.sender.id, { "text": "message_test"}, "NON_PROMOTIONAL_SUBSCRIPTION", (error, body) => {
    // ...
});

### CODE REVIEW

**Comment by eXeDK** [comment]
Please fix tests @baudev

**Comment by eXeDK** [comment]
What about Node4? I have not setup these pipelines so I'm not sure I can make changes to those. 
Maybe @remixz can.

**Comment by baudev** [comment]
The mentioned errors in Node4 doesn't seem to be link

**Comment by baudev** [comment]
The function could be used as following finally : 
```javascript
bot.sendMessage(payload.sender.id, {"text": "message_test"},  (error, body) => {
    // ...
}, 'MESSAGE_TAG', 'NON_PROMOTIONAL_SUBSCRIPTION');
```

**Comment by baudev** [comment]
This issue's comment https://github.com/istanbuljs/nyc/issues/865#issuecomment-398435383 explains that `node 4.x` is no more supported with the latest versions of `nyc`. This is confirmed by the following commit: https://github.com/istanbuljs/nyc/commit/19b7d2130556b939bdd2fb69c2a35d09fe83f61e 

We have two options:
- Drops support for `node 4.x` and then this test in Travis
- Specify the version of `nyc`. As `nyc` is a dependency of `tap` we should [specify the version of the latter](https://github.com/remixz/messenger-bot/blob/master/package.json#L32).

I prefer the last solution: easier and more secure. Then it requires that @remixz remove the `node 4` test in his Travis account.

What do you think about @eXeDK ?

**Comment by baudev** [comment]
I tried everything. I think that specifying the `tap` version doesn't work due to the Travis cache. Anyway. 
@remixz should remove the `Node4` test or maybe @eXeDK have the rights of editing/remove/add tests ?

**Comment by eXeDK** [comment]
I'll merge this and try and fix the tests afterwards @baudev

**Pull request merged**
