### PR TITLE
Updated Graph API version

### PR DESCRIPTION
**Pull request by magnusburton**
Thought this lib needed a version-bump. Maybe we should make the graph api version into a variable?

### CODE REVIEW

**Comment by eXeDK** [comment]
Please fix the tests as well. Is the functionality confirmed to be working still as well?

**Comment by magnusburton** [comment]
@eXeDK Yeah the Graph version bump didn't change the functionality of the requests

**Comment by eXeDK** [comment]
@magnusburton if you are still using this package. Are you interested in helping getting this package up to speed and maintaining it? 
Unfortunately I don't have the required time to do all of the job myself.

**Comment by eXeDK** [comment]
Updated the Graph API to 2.12 instead :-)

**Pull request closed without merging**
